### ISSUE TITLE
[Bug] All-Pass filter can lead to high frequency pitch buildup

### ISSUE THREAD

**Issue by amlib** [lsp-plugins/lsp-plugins#358] opened 2023-12-22 06:49 UTC
Using an All-Pass filter in Parametric EQ LR x16 (may happen on other plugins) can lead to a very high frequency pitch building up over time. This almost fried my twitter :(

It seems to build up very slowly and only while there is sound being played, however you should be able to spot the signal growing from -inf to -119db  within a few minutes on the EQ`s own meter. The pitch will go away if you mute/disable the filter, but it will build up again once unmuted/re-enabled.

I've attached a file with the exact settings I was using in case it requires something closer to my setup to properly reproduce. (please remove .txt from file name, github is silly and wouldn't allow .cfg to be uploaded)

linux: 6.6.7-4-MANJARO
lsp-plugins-lv2: 1.2.13-1

[borked.cfg.txt](https://github.com/sadko4u/lsp-plugins/files/13749137/borked.cfg.txt)

**Comment by sadko4u** [comment] 2023-12-22 14:57
What's your maximum level you get with such setup?
-119 dB looks like a floating-point rounding error noise.

**Comment by amlib** [comment] 2023-12-22 15:45
The maximum level that the pitch achieved? I don't know precisely since when it first happened I was panicking a little trying to understand why my twitter was making weird noises, but the eq meter went really high, probably something like -10db. As I said it builds up over time, when trying to reproduce this issue I observed it growing up -90db, so I concluded that if left unattended for a while it would again reach the "dangerous" level it once reached.

**Comment by sadko4u** [comment] 2024-02-18 11:35
Hello! I've just pushed another implementation of RLC allpass filters. Are you available to build the development branch for tests?

**Comment by amlib** [comment] 2024-02-23 18:46
Hi, I'm willing to test it. Sorry for only seeing it now. I'm using Manjaro with access to the AUR, if It is just modifying a PKGBUILD to use the development branch it should be a piece of cake to test it.

**Comment by amlib** [comment] 2024-02-24 22:44
I've compiled the dev version and observed the same problem. I've used the same EQ settings as the original post and just played music into the EQ. every couple minutes I would pause the music and observe that the pitch had grown a bit more. After about one hour the spectrun analyzer was already showing the pitch at -39db at 22006.9hz (it wont measure any higher than that frequency).

Also, I would like to point out that I run my system at 44.1khz, maybe the behavior is different on more common 48khz?

![image](https://github.com/lsp-plugins/lsp-plugins/assets/3516260/7b9c2e51-753a-41e7-85ca-9603efba6979)

**Comment by sadko4u** [comment] 2024-02-25 08:51
> Also, I would like to point out that I run my system at 44.1khz, maybe the behavior is different on more common 48khz?

No, this should not take any effect.

**Comment by sadko4u** [comment] 2024-02-25 15:12
Today I've reproduced the case. And it really seems to be a floating-point rounding error accumulated in allpass filter's memory. I'll try to play around to find the workaround.

**Comment by sadko4u** [comment] 2024-02-25 20:11
I've noticed that if I use only allpass filter from your setup, it doesn't blow up the nyquist frequency.

**Comment by sadko4u** [comment] 2024-02-25 22:06
It seems that equalizer smoothing mode introduced for avoiding pops and clicks when changing parameters of filters like Frequency, Gain and Q factor worked improperly.

I can not reproduce the problem any more after these commits:
https://github.com/lsp-plugins/lsp-plugins-para-equalizer/commit/a32854c56be2d91ce61a50c39fa6c11943bbf196
https://github.com/lsp-plugins/lsp-plugins-filter/commit/652fa15e03958bc017f9b8b3b6de3019bbf26929

**Comment by amlib** [comment] 2024-02-28 00:29
I've been able to reproduce the issue in other plugins, more specifically the  LSP Filter Mono and Stereo versions. I wonder if this could be a problem with SIMD extensions? Is there an easy way to force the build (like a config flag) to use a different code path without something like SSE or perhaps AVX? I could test this, if you want to.

**Comment by sadko4u** [comment] 2024-02-28 12:33
I don't think it's SIMD-related. I still consider it being just a rounding error in floating-point computations. I think just doing some small alteration of one of filter coefficients of all-pass filter can fix self-explosion of the filter.

**Comment by sadko4u** [comment] 2024-02-29 22:22
Hello!

Today I've reviewed allpass filter implementation and found the reason of the problem.
The original design provided one pole and one zero for your case but after bilinear transformation of the RLC filter it seems that the code computed improper poles and zeros on the Z plane. That made filter unstable and allowed the filter to build up.
Adding just one additional pole and one additional zero that cancels this pole in the analog representation of the filter made the bilinear transformation valid.

I've pushed changes to git, please try.

**Comment by amlib** [comment] 2024-03-02 09:08
I've been testing the new version for about one hour and so far no issues! Seems like it is solved. Many thanks!

I've also been daily driving the devel branch on a big DSP chain with quite a few LSP plugins, haven't noticed any regressions.

**Comment by sadko4u** [comment] 2024-03-06 00:42
Fixed in 1.2.15.

**Closed** 2024-03-06 00:45 UTC
Labels: bug
