### ISSUE TITLE
Disbalance between left and right channels with para-eq-stereo

### ISSUE THREAD

**Issue by whitespace-rebel** [lsp-plugins/lsp-plugins#452] opened 2024-10-22 10:34 UTC
Hello everyone,

when changing the frequency or gain in para-eq-stereo a disbalace is created between left and right channels.
It is especially noticable when typin in values that are far away from the previous value (change 20 Hz to 2000 Hz with high pass filter or gain -1 dB to -20 dB with high shelf). Test it with a mono signal to better see it.

Also the curve of the resulting EQ has a slightly wrong shape.

It is possible to fix it temporarily by changing Slope to 2x and back to 1x.

filter-stereo is also affected
I did not test graph-eq

I hope someone is able to reproduce this bug.

Tested VST2 and VST3 with version 1.2.17
Debian 12

Thank you!

**Comment by sadko4u** [comment] 2024-10-22 10:38
Hello!

Have you tried to reproduce the problem with the latest release 1.2.19?

Also, what means "the curve of the resulting EQ has a slightly wrong shape"?

**Comment by whitespace-rebel** [comment] 2024-10-22 10:45
> Have you tried to reproduce the problem with the latest release 1.2.19?
Not yet. I will soon. Many previous versions are affected, too.

> Also, what means "the curve of the resulting EQ has a slightly wrong shape"?
I think the curve is not updated properly, when chanhing a value (freq or gain). But after changing Slope from 1x to 2x and back to 1x, you should notice a tiny change in the slope/position of the curve.

**Comment by whitespace-rebel** [comment] 2024-10-22 11:21
Version 1.2.19 is also affected.

**Comment by sadko4u** [comment] 2024-10-22 11:23
What host do you use?

**Comment by sadko4u** [comment] 2024-10-22 19:19
I could reproduce the 'imprecise' spectrum graph. The latest commit to the parametric equalizer should fix this: https://github.com/lsp-plugins/lsp-plugins-para-equalizer/commit/95249a33c07a3efa0bebc228b17e97d5dc525b46

But I can not reproduce the disbalance between left and right channel on the development version of Parametric Equalizer plugin which is based on 1.2.19 release.
How do I check:
- I create a mono bus with pink noise and route it to left and right channels of a stereo bus;
- On the stereo bus, I hear the pink noise;
- I configure pan control of the stereo bus to mix left and right channels to mono and inverse phase of one input;
- Now I don't hear anything because the left and right channels cancel each other;
- I put parametric equalizer stereo on this bus and set low-pass filter at 50 Hz;
- I enter the 5000 Hz value to low-pass filter and force it to apply the changes;
- Still I don't hear anything, the right and left channels continue to cancel each other;
- The same is true for Hi-pass and Hi-shelf filters.

How did you find out the disbalance between left and right channels?

**Comment by sadko4u** [comment] 2024-10-22 19:24
Ok, I could reproduce the problem. But the patch I've mentioned above has fixed it.

**Comment by whitespace-rebel** [comment] 2024-10-23 03:49
Thank you!

**Comment by sadko4u** [comment] 2024-12-20 23:41
Fixed in 1.2.20!

**Closed by sadko4u** 2024-12-20 23:41 UTC
Labels: bug
