### ISSUE TITLE
GUI File Browser - Cursor keeps on advancing on its own when using down arrow

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#469] opened 2024-11-24 22:26 UTC
Possible Bug
lsp-plugins-1.2.19-Linux-x86_64

GUI file browser found in Sampler and IR based plugins.

`Steps To Reproduce:`
-In Ardour load up for example the Multi Sampler plugin
-Load a sample into the waveform pane so that GUI file browser is shown
-Click on the "keyboard" icon in upper right hand corner of plugin window to allow keyboard override.
-Click mouse on the top audio file in GUI file browser so cursor is at the top
-When you hit the down arrow a couples times, seems that when you get to the third item, all of a sudden the cursor then keeps on advancing by itself.  Continues to go down to the next item over and over until no longer visible.

Would someone be willing to verify that this happens on their machine.

Thank You

There appears to be something wrong in general with plugin + Ardour keyboard icon, hard to narrow down.  
Here is a similar post that also happens #470

**Comment by sadko4u** [comment] 2024-12-01 18:58
The problem was related to the key auto-repeat simulation by the `ListBox` widget. Seems that auto-repeat is simulation is not necessary any more. I've removed it and can not reproduce the problem any more.

**Comment by sadko4u** [comment] 2024-12-20 23:44
Fixed in 1.2.20!

**Closed by sadko4u** 2024-12-20 23:44 UTC
Labels: bug

**Comment by audio2000** [comment] 2024-12-25 00:56
@sadko4u
I just wanted to thank you guys for working on the bug fixes / updates for the posts I made, in the most recent release (1.2.20)
